apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      args:
        - --dbpath
        - /data/db
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: 'adminuser'
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: 'password123'
      livenessProbe:
        exec:
          command: 
            - mongo
            - --disableImplicitSessions
            - --eval
            - "db.adminCommand('ping')"
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        exec:
          command:
            - mongo
            - --disableImplicitSessions
            - --eval
            - "db.adminCommand('ping')"
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
