apiVersion: v1
kind: Pod
metadata:
  name: pod-command-hello
  labels:
    app: frontend
spec:
  containers:
  - name: c1
    image: ubuntu
    command:
    - /bin/sh
    - -ec
    - "while :; do echo 'HELLOO WORLD'; sleep 3; done"
