apiVersion: v1
kind: Pod
metadata:
  name: initpod
spec:
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
    - name: init-mydb
      image: busybox
      command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
  containers:
    - name: myapp-main
      image: busybox
      command: ['sh', '-c', 'echo ANA UYGULAMA CALISMAYA BASLADI && sleep 3600']