apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod  
spec:
  containers:
    - name: affinitycontainer
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disksize
                operator: In
                values:
                  - large
                  - medium
