apiVersion: v1
kind: Pod
metadata:
  name: tcpsocketprobe-tomcat
spec:
  containers:
    - name: tcpsocketprobe-tomcat
      image: tomcat:8.0
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
